requests:
  allowed:
    any:
      number: 2
      withinmillis: 120000
    rejected:
      withinmillis: 30000


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:persondb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
